info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    SeedLot:
      allOf:
      - $ref: '#/components/schemas/SeedLotNewRequest'
      - type: object
        x-brapi-metadata:
          primaryModel: true
          module: BrAPI-Germplasm
        properties: 
          seedLotDbId:
            description: Unique DbId for the Seed Lot
            type: string
            example: 261ecb09
        required:
        - seedLotDbId

