info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    PlateFormat:
      description: Enum for plate formats, usually "PLATE_96" for a 96 well plate or "TUBES" for plateless format
      enum:
      - PLATE_96
      - TUBES
      type: string
      example: PLATE_96

