info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Plate:
      allOf:
      - $ref: '#/components/schemas/PlateNewRequest'
      - type: object
        x-brapi-metadata:
          primaryModel: true
          module: BrAPI-Genotyping
        properties:
          plateDbId:
            description: The ID which uniquely identifies a `Plate`
            type: string
            example: a106467f

