info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /delete/observations:
    post:
      summary: Submit a delete request for `Observations`
      description: |-
        Submit a search delete for `Observations`
      parameters:
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObservationSearchRequest'
      responses:
        '200':
          $ref: '#/components/responses/ObservationListResponse'
        '202':
          $ref: '#/components/responses/202AcceptedSearchResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Observations
