info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Study:
      allOf:
      - $ref: '#/components/schemas/StudyNewRequest'
      - type: object
        x-brapi-metadata:
          primaryModel: true
          module: BrAPI-Core
        required:
        - studyDbId
        properties:
          studyDbId:
            description: |-
              The ID which uniquely identifies a study within the given database server
              
              MIAPPE V1.1 (DM-11) Study unique ID - Unique identifier comprising the name or identifier for the institution/database hosting the submission of the study data, and the identifier of the study in that institution.
            type: string
            example: 175ac75a
