info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /seedlots/{seedLotDbId}/transactions:
    get:
      summary: Get all Transactions related to a specific Seed Lot
      description: Get all Transactions related to a specific Seed Lot
      parameters:
      - name: seedLotDbId
        description: Unique id for a seed lot on this server
        in: path
        required: true
        schema:
          type: string
      - name: transactionDbId
        description: Unique id for a Transaction that has occurred
        in: query
        required: false
        schema:
          type: string
      - name: transactionDirection
        description: Filter results to only include transactions directed to the specific Seed Lot (TO), away from the specific Seed Lot (FROM), or both (BOTH). The default value for this parameter is BOTH
        in: query
        required: false
        schema:
          type: string
          enum:
          - TO
          - FROM
          - BOTH
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/SeedLotTransactionListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
      tags:
      - Seed Lots