info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    ScaleBaseClass:
      type: object
      description: Scale metadata
      required:
      - scaleName
      properties:
        additionalInfo:
          additionalProperties:
            type: string
          description: Additional arbitrary info
          type: object
        dataType:
          $ref: '#/components/schemas/TraitDataType'
        decimalPlaces:
          description: For numerical, number of decimal places to be reported
          type: integer
          example: 2
        ontologyReference:
          $ref: '#/components/schemas/OntologyReference'
        scaleName:
          description: |- 
            Name of the scale
            
            MIAPPE V1.1 (DM-92) Scale Name of the scale associated with the variable
          type: string
          example: Meters
        units:
          description: |-
            This field can be used to describe the units used for this scale. This should be the abriviated 
            form of the units, intended to be displayed with every value using this scale. Usually this only 
            applies when `dataType` is Numeric, but could also be included for other dataTypes when applicable.
          type: string
          example: m
        validValues:
          type: object
          properties:
            categories: 
              description: List of possible values with optional labels
              items:
                type: object
                properties:
                  label:
                    type: string 
                    description: A text label for a category
                  value:
                    type: string
                    description: The actual value for a category
              type: array
              example: 
                - value: "0"
                  label: "low"
                - value: "5"
                  label: "medium"
                - value: "10"
                  label: "high"
            max:
              description: Maximum value (used for field data capture control).
              type: integer
              example: 9999
            min:
              description: Minimum value (used for data capture control) for numerical and date scales
              type: integer
              example: 2
        externalReferences: 
          $ref: '#/components/schemas/ExternalReferences'

