info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Program:
      allOf:
      - $ref: '#/components/schemas/ProgramNewRequest'
      - type: object
        x-brapi-metadata:
          primaryModel: true
          module: BrAPI-Core
        required:
        - programDbId
        properties:
          programDbId:
            description: The ID which uniquely identifies the program
            type: string
            example: f60f15b2

