info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Cross:
      allOf:
        - $ref: '#/components/schemas/CrossNewRequest'
        - type: object
          x-brapi-metadata:
            primaryModel: true
            module: BrAPI-Germplasm
          properties:
            crossDbId:
              description: the unique identifier for a cross
              type: string
              example: d105fd6f