info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    CrossParent:
      type: object
      properties:
        germplasmDbId: 
          description: the unique identifier for a germplasm
          type: string
          example: d34b10c3
        germplasmName: 
          description: the human readable name for a germplasm
          type: string
          example: TME_419
        observationUnitDbId: 
          description: the unique identifier for an observation unit
          type: string
          example: 2e1926a7
        observationUnitName: 
          description: the human readable name for an observation unit
          type: string
          example: my_Plot_9001
        parentType: 
          description: The type of parent ex. 'MALE', 'FEMALE', 'SELF', 'POPULATION', etc.
          enum:
          - MALE
          - FEMALE
          - SELF
          - POPULATION
          type: string
          example: MALE