info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Trial:
      allOf:
      - $ref: '#/components/schemas/TrialNewRequest'
      - type: object
        x-brapi-metadata:
          primaryModel: true
          module: BrAPI-Core
        required:
        - trialDbId
        properties:
          trialDbId:
            description: |-
              The ID which uniquely identifies a trial
              
              MIAPPE V1.1 (DM-2) Investigation unique ID - Identifier comprising the unique name of the institution/database hosting the submission of the investigation data, and the accession number of the investigation in that institution.
            type: string
            example: 1883b402

