info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    ListTypes:
      description: A flag to indicate the type of objects that are referneced in a List 
      type: string
      example: germplasm
      enum:
      - germplasm
      - markers
      - variants
      - programs
      - trials
      - studies
      - observationUnits
      - observations
      - observationVariables
      - samples

