info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components: 
  schemas:
    ListDetails:
      allOf:
      - $ref: '#/components/schemas/ListSummary'
      - $ref: '#/components/schemas/ListNewRequest'
      - type: object
        x-brapi-metadata:
          primaryModel: true
          module: BrAPI-Core
          title: List
        properties: {}
