info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    VariantSetsExtractRequest:
      allOf:
      - $ref: '#/components/schemas/SearchRequestParametersStudies'
      - type: object
        description: Request object for extracting data subsets as new Variant Sets
        properties:
          callSetDbIds: 
            description: The CallSet to search.
            type: array
            items:
              type: string
            example: ['9569cfc4', 'da1e888c']
          variantDbIds: 
            description: The Variant to search.
            type: array
            items:
              type: string
            example: ['c80f068b', 'eb7c5f50']
          variantSetDbIds: 
            description: The VariantSet to search.
            type: array
            items:
              type: string
            example: ['b2903842', 'dcbb8558']
          expandHomozygotes:
            description: Should homozygotes be expanded (true) or collapsed into a single occurrence (false)
            type: boolean
            example: true
          sepPhased:
            description: The string used as a separator for phased allele calls.
            type: string
            example: '~'
          sepUnphased:
            description: The string used as a separator for unphased allele calls.
            type: string
            example: '|'
          unknownString:
            description: The string used as a representation for missing data.
            type: string
            example: '-'