info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Season: 
      type: object
      x-brapi-metadata:
        primaryModel: true
        module: BrAPI-Core
      required:
      - seasonDbId
      properties:
        seasonName:
          description: Name of the season. ex. 'Spring', 'Q2', 'Season A', etc.
          type: string
          example: Spring
        seasonDbId:
          description: The ID which uniquely identifies a season. For backward compatibility it can be a string like '2012', '1957-2004'
          type: string
          example: Spring_2018
        year:
          description: The 4 digit year of the season.
          type: integer
          example: 2018

