info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  parameters:
    observationUnitLevelName:
      description: |-
        The Observation Unit Level. Returns only the observation unit of the specified Level. 
        References ObservationUnit->observationUnitPosition->observationLevel->levelName 

        **Standard Level Names: study, field, entry, rep, block, sub-block, plot, sub-plot, plant, pot, sample** 

        For more information on Observation Levels, please review the <a target="_blank" href="https://wiki.brapi.org/index.php/Observation_Levels">Observation Levels documentation</a>. 
      in: query
      name: observationUnitLevelName
      required: false
      schema:
        type: string
    observationUnitLevelOrder:
      description: |-
        The Observation Unit Level Order Number. Returns only the observation unit of the specified Level. 
        References ObservationUnit->observationUnitPosition->observationLevel->levelOrder 

        For more information on Observation Levels, please review the <a target="_blank" href="https://wiki.brapi.org/index.php/Observation_Levels">Observation Levels documentation</a>. 
      in: query
      name: observationUnitLevelOrder
      required: false
      schema:
        type: string
    observationUnitLevelCode:
      description: |-
        The Observation Unit Level Code. This parameter should be used together with `observationUnitLevelName` 
        or `observationUnitLevelOrder`. References ObservationUnit->observationUnitPosition->observationLevel->levelCode 

        For more information on Observation Levels, please review the <a target="_blank" href="https://wiki.brapi.org/index.php/Observation_Levels">Observation Levels documentation</a>. 
      in: query
      name: observationUnitLevelCode
      required: false
      schema:
        type: string
    observationUnitLevelRelationshipName:
      description: |-
        The Observation Unit Level Relationship is a connection that this observation unit has to another level of the hierarchy. 
        For example, if you have several observation units at a 'plot' level, they might all share a relationship to the same 'field' level.  
        Use this parameter to identify groups of observation units that share a relationship level. 

        **Standard Level Names: study, field, entry, rep, block, sub-block, plot, sub-plot, plant, pot, sample** 

        For more information on Observation Levels, please review the <a target="_blank" href="https://wiki.brapi.org/index.php/Observation_Levels">Observation Levels documentation</a>. 
      in: query
      name: observationUnitLevelRelationshipName
      required: false
      schema:
        type: string
    observationUnitLevelRelationshipOrder:
      description: |-
        The Observation Unit Level Order Number. Returns only the observation unit of the specified Level. 
        References ObservationUnit->observationUnitPosition->observationLevel->levelOrder 

        For more information on Observation Levels, please review the <a target="_blank" href="https://wiki.brapi.org/index.php/Observation_Levels">Observation Levels documentation</a>. 
      in: query
      name: observationUnitLevelRelationshipOrder
      required: false
      schema:
        type: string
    observationUnitLevelRelationshipCode:
      description: |-
        The Observation Unit Level Code. This parameter should be used together with `observationUnitLevelName` 
        or `observationUnitLevelOrder`. References ObservationUnit->observationUnitPosition->observationLevel->levelCode 

        For more information on Observation Levels, please review the <a target="_blank" href="https://wiki.brapi.org/index.php/Observation_Levels">Observation Levels documentation</a>. 
      in: query
      name: observationUnitLevelRelationshipCode
      required: false
      schema:
        type: string

