info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    CrossingProject:
      allOf:
        - $ref: '#/components/schemas/CrossingProjectNewRequest'
        - type: object
          x-brapi-metadata:
            primaryModel: true
            module: BrAPI-Germplasm
          properties:
            crossingProjectDbId:
              description: The unique identifier for a crossing project
              type: string
              example: ce0e1c29