info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Image:
      allOf:
      - $ref: '#/components/schemas/ImageNewRequest'
      - type: object
        x-brapi-metadata:
          primaryModel: true
          module: BrAPI-Phenotyping
        properties:
          imageDbId:
            description: The unique identifier of an image
            type: string
            example: a55efb9c
